//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private int AgeField;
        
        private float WeightField;
        
        private char GenderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public char Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PressureReading", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PressureReading : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReadingOrderField;
        
        private int HighField;
        
        private int LowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReadingOrder {
            get {
                return this.ReadingOrderField;
            }
            set {
                if ((this.ReadingOrderField.Equals(value) != true)) {
                    this.ReadingOrderField = value;
                    this.RaisePropertyChanged("ReadingOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int High {
            get {
                return this.HighField;
            }
            set {
                if ((this.HighField.Equals(value) != true)) {
                    this.HighField = value;
                    this.RaisePropertyChanged("High");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Low {
            get {
                return this.LowField;
            }
            set {
                if ((this.LowField.Equals(value) != true)) {
                    this.LowField = value;
                    this.RaisePropertyChanged("Low");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertData", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.insertDataResponse insertData(WindowsFormsApp1.ServiceReference1.insertDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertData", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertDataResponse> insertDataAsync(WindowsFormsApp1.ServiceReference1.insertDataRequest request);
        
        // CODEGEN: Generating message contract since element name ViewUserInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserInfo", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse ViewUserInfo(WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse> ViewUserInfoAsync(WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse UpdateUserInfo(WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse> UpdateUserInfoAsync(WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.getIDResponse getID(WindowsFormsApp1.ServiceReference1.getIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getID", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getIDResponse> getIDAsync(WindowsFormsApp1.ServiceReference1.getIDRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUsernameAvailability", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse checkUsernameAvailability(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUsernameAvailability", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse> checkUsernameAvailabilityAsync(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkPassword", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.checkPasswordResponse checkPassword(WindowsFormsApp1.ServiceReference1.checkPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkPasswordResponse> checkPasswordAsync(WindowsFormsApp1.ServiceReference1.checkPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserPressureReadingsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPressureReadings", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse GetUserPressureReadings(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPressureReadings", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse> GetUserPressureReadingsAsync(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest request);
        
        // CODEGEN: Generating message contract since element name Date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPressureData", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.insertPressureDataResponse insertPressureData(WindowsFormsApp1.ServiceReference1.insertPressureDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertPressureData", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertPressureDataResponse> insertPressureDataAsync(WindowsFormsApp1.ServiceReference1.insertPressureDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertData", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.insertDataRequestBody Body;
        
        public insertDataRequest() {
        }
        
        public insertDataRequest(WindowsFormsApp1.ServiceReference1.insertDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float weight;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public char gender;
        
        public insertDataRequestBody() {
        }
        
        public insertDataRequestBody(string username, string password, int age, float weight, char gender) {
            this.username = username;
            this.password = password;
            this.age = age;
            this.weight = weight;
            this.gender = gender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.insertDataResponseBody Body;
        
        public insertDataResponse() {
        }
        
        public insertDataResponse(WindowsFormsApp1.ServiceReference1.insertDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertDataResponseBody {
        
        public insertDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewUserInfoRequestBody Body;
        
        public ViewUserInfoRequest() {
        }
        
        public ViewUserInfoRequest(WindowsFormsApp1.ServiceReference1.ViewUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public ViewUserInfoRequestBody() {
        }
        
        public ViewUserInfoRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ViewUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ViewUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.ViewUserInfoResponseBody Body;
        
        public ViewUserInfoResponse() {
        }
        
        public ViewUserInfoResponse(WindowsFormsApp1.ServiceReference1.ViewUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.UserInfo ViewUserInfoResult;
        
        public ViewUserInfoResponseBody() {
        }
        
        public ViewUserInfoResponseBody(WindowsFormsApp1.ServiceReference1.UserInfo ViewUserInfoResult) {
            this.ViewUserInfoResult = ViewUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequestBody Body;
        
        public UpdateUserInfoRequest() {
        }
        
        public UpdateUserInfoRequest(WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float weight;
        
        public UpdateUserInfoRequestBody() {
        }
        
        public UpdateUserInfoRequestBody(int id, string username, int age, float weight) {
            this.id = id;
            this.username = username;
            this.age = age;
            this.weight = weight;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponseBody Body;
        
        public UpdateUserInfoResponse() {
        }
        
        public UpdateUserInfoResponse(WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserInfoResponseBody {
        
        public UpdateUserInfoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getID", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getIDRequestBody Body;
        
        public getIDRequest() {
        }
        
        public getIDRequest(WindowsFormsApp1.ServiceReference1.getIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getIDRequestBody() {
        }
        
        public getIDRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.getIDResponseBody Body;
        
        public getIDResponse() {
        }
        
        public getIDResponse(WindowsFormsApp1.ServiceReference1.getIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getIDResult;
        
        public getIDResponseBody() {
        }
        
        public getIDResponseBody(int getIDResult) {
            this.getIDResult = getIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUsernameAvailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUsernameAvailability", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequestBody Body;
        
        public checkUsernameAvailabilityRequest() {
        }
        
        public checkUsernameAvailabilityRequest(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUsernameAvailabilityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public checkUsernameAvailabilityRequestBody() {
        }
        
        public checkUsernameAvailabilityRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkUsernameAvailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkUsernameAvailabilityResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponseBody Body;
        
        public checkUsernameAvailabilityResponse() {
        }
        
        public checkUsernameAvailabilityResponse(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkUsernameAvailabilityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkUsernameAvailabilityResult;
        
        public checkUsernameAvailabilityResponseBody() {
        }
        
        public checkUsernameAvailabilityResponseBody(bool checkUsernameAvailabilityResult) {
            this.checkUsernameAvailabilityResult = checkUsernameAvailabilityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkPassword", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.checkPasswordRequestBody Body;
        
        public checkPasswordRequest() {
        }
        
        public checkPasswordRequest(WindowsFormsApp1.ServiceReference1.checkPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public checkPasswordRequestBody() {
        }
        
        public checkPasswordRequestBody(string username, string Password) {
            this.username = username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.checkPasswordResponseBody Body;
        
        public checkPasswordResponse() {
        }
        
        public checkPasswordResponse(WindowsFormsApp1.ServiceReference1.checkPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool checkPasswordResult;
        
        public checkPasswordResponseBody() {
        }
        
        public checkPasswordResponseBody(bool checkPasswordResult) {
            this.checkPasswordResult = checkPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPressureReadingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPressureReadings", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequestBody Body;
        
        public GetUserPressureReadingsRequest() {
        }
        
        public GetUserPressureReadingsRequest(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPressureReadingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserPressureReadingsRequestBody() {
        }
        
        public GetUserPressureReadingsRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserPressureReadingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserPressureReadingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponseBody Body;
        
        public GetUserPressureReadingsResponse() {
        }
        
        public GetUserPressureReadingsResponse(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserPressureReadingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServiceReference1.PressureReading[] GetUserPressureReadingsResult;
        
        public GetUserPressureReadingsResponseBody() {
        }
        
        public GetUserPressureReadingsResponseBody(WindowsFormsApp1.ServiceReference1.PressureReading[] GetUserPressureReadingsResult) {
            this.GetUserPressureReadingsResult = GetUserPressureReadingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPressureDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPressureData", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.insertPressureDataRequestBody Body;
        
        public insertPressureDataRequest() {
        }
        
        public insertPressureDataRequest(WindowsFormsApp1.ServiceReference1.insertPressureDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertPressureDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Order;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int High;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Low;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Date;
        
        public insertPressureDataRequestBody() {
        }
        
        public insertPressureDataRequestBody(int Id, int Order, int High, int Low, string Date) {
            this.Id = Id;
            this.Order = Order;
            this.High = High;
            this.Low = Low;
            this.Date = Date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertPressureDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertPressureDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.insertPressureDataResponseBody Body;
        
        public insertPressureDataResponse() {
        }
        
        public insertPressureDataResponse(WindowsFormsApp1.ServiceReference1.insertPressureDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertPressureDataResponseBody {
        
        public insertPressureDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp1.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebService1Soap>, WindowsFormsApp1.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.insertDataResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.insertData(WindowsFormsApp1.ServiceReference1.insertDataRequest request) {
            return base.Channel.insertData(request);
        }
        
        public void insertData(string username, string password, int age, float weight, char gender) {
            WindowsFormsApp1.ServiceReference1.insertDataRequest inValue = new WindowsFormsApp1.ServiceReference1.insertDataRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.insertDataRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.gender = gender;
            WindowsFormsApp1.ServiceReference1.insertDataResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).insertData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertDataResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.insertDataAsync(WindowsFormsApp1.ServiceReference1.insertDataRequest request) {
            return base.Channel.insertDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertDataResponse> insertDataAsync(string username, string password, int age, float weight, char gender) {
            WindowsFormsApp1.ServiceReference1.insertDataRequest inValue = new WindowsFormsApp1.ServiceReference1.insertDataRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.insertDataRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            inValue.Body.gender = gender;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).insertDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewUserInfo(WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest request) {
            return base.Channel.ViewUserInfo(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.UserInfo ViewUserInfo(int Id) {
            WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewUserInfoRequestBody();
            inValue.Body.Id = Id;
            WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewUserInfo(inValue);
            return retVal.Body.ViewUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.ViewUserInfoAsync(WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest request) {
            return base.Channel.ViewUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.ViewUserInfoResponse> ViewUserInfoAsync(int Id) {
            WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest inValue = new WindowsFormsApp1.ServiceReference1.ViewUserInfoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.ViewUserInfoRequestBody();
            inValue.Body.Id = Id;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).ViewUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateUserInfo(WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfo(request);
        }
        
        public void UpdateUserInfo(int id, string username, int age, float weight) {
            WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateUserInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.UpdateUserInfoAsync(WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.UpdateUserInfoResponse> UpdateUserInfoAsync(int id, string username, int age, float weight) {
            WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest inValue = new WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.UpdateUserInfoRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.age = age;
            inValue.Body.weight = weight;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).UpdateUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.getIDResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.getID(WindowsFormsApp1.ServiceReference1.getIDRequest request) {
            return base.Channel.getID(request);
        }
        
        public int getID(string username) {
            WindowsFormsApp1.ServiceReference1.getIDRequest inValue = new WindowsFormsApp1.ServiceReference1.getIDRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getIDRequestBody();
            inValue.Body.username = username;
            WindowsFormsApp1.ServiceReference1.getIDResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getID(inValue);
            return retVal.Body.getIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getIDResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.getIDAsync(WindowsFormsApp1.ServiceReference1.getIDRequest request) {
            return base.Channel.getIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.getIDResponse> getIDAsync(string username) {
            WindowsFormsApp1.ServiceReference1.getIDRequest inValue = new WindowsFormsApp1.ServiceReference1.getIDRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.getIDRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).getIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.checkUsernameAvailability(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest request) {
            return base.Channel.checkUsernameAvailability(request);
        }
        
        public bool checkUsernameAvailability(string username) {
            WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest inValue = new WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequestBody();
            inValue.Body.username = username;
            WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).checkUsernameAvailability(inValue);
            return retVal.Body.checkUsernameAvailabilityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.checkUsernameAvailabilityAsync(WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest request) {
            return base.Channel.checkUsernameAvailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityResponse> checkUsernameAvailabilityAsync(string username) {
            WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest inValue = new WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.checkUsernameAvailabilityRequestBody();
            inValue.Body.username = username;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).checkUsernameAvailabilityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.checkPasswordResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.checkPassword(WindowsFormsApp1.ServiceReference1.checkPasswordRequest request) {
            return base.Channel.checkPassword(request);
        }
        
        public bool checkPassword(string username, string Password) {
            WindowsFormsApp1.ServiceReference1.checkPasswordRequest inValue = new WindowsFormsApp1.ServiceReference1.checkPasswordRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.checkPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.Password = Password;
            WindowsFormsApp1.ServiceReference1.checkPasswordResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).checkPassword(inValue);
            return retVal.Body.checkPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkPasswordResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.checkPasswordAsync(WindowsFormsApp1.ServiceReference1.checkPasswordRequest request) {
            return base.Channel.checkPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.checkPasswordResponse> checkPasswordAsync(string username, string Password) {
            WindowsFormsApp1.ServiceReference1.checkPasswordRequest inValue = new WindowsFormsApp1.ServiceReference1.checkPasswordRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.checkPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.Password = Password;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).checkPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.GetUserPressureReadings(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest request) {
            return base.Channel.GetUserPressureReadings(request);
        }
        
        public WindowsFormsApp1.ServiceReference1.PressureReading[] GetUserPressureReadings(int id) {
            WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest inValue = new WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).GetUserPressureReadings(inValue);
            return retVal.Body.GetUserPressureReadingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.GetUserPressureReadingsAsync(WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest request) {
            return base.Channel.GetUserPressureReadingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsResponse> GetUserPressureReadingsAsync(int id) {
            WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest inValue = new WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.GetUserPressureReadingsRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).GetUserPressureReadingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.insertPressureDataResponse WindowsFormsApp1.ServiceReference1.WebService1Soap.insertPressureData(WindowsFormsApp1.ServiceReference1.insertPressureDataRequest request) {
            return base.Channel.insertPressureData(request);
        }
        
        public void insertPressureData(int Id, int Order, int High, int Low, string Date) {
            WindowsFormsApp1.ServiceReference1.insertPressureDataRequest inValue = new WindowsFormsApp1.ServiceReference1.insertPressureDataRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.insertPressureDataRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Order = Order;
            inValue.Body.High = High;
            inValue.Body.Low = Low;
            inValue.Body.Date = Date;
            WindowsFormsApp1.ServiceReference1.insertPressureDataResponse retVal = ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).insertPressureData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertPressureDataResponse> WindowsFormsApp1.ServiceReference1.WebService1Soap.insertPressureDataAsync(WindowsFormsApp1.ServiceReference1.insertPressureDataRequest request) {
            return base.Channel.insertPressureDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.insertPressureDataResponse> insertPressureDataAsync(int Id, int Order, int High, int Low, string Date) {
            WindowsFormsApp1.ServiceReference1.insertPressureDataRequest inValue = new WindowsFormsApp1.ServiceReference1.insertPressureDataRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.insertPressureDataRequestBody();
            inValue.Body.Id = Id;
            inValue.Body.Order = Order;
            inValue.Body.High = High;
            inValue.Body.Low = Low;
            inValue.Body.Date = Date;
            return ((WindowsFormsApp1.ServiceReference1.WebService1Soap)(this)).insertPressureDataAsync(inValue);
        }
    }
}
